### ISSUE TITLE
[Feature Request] Allow second tab row to be aligned to the left

### ISSUE THREAD

**Issue by forever-and-a-day** [DragonPlayerX/TabExtension#1]
Imo one or two tabs in the middle of the second row looks kinda ugly, it would be nice if you could choose to align second row tabs to the left (or right).

**Comment by DragonPlayerX** [comment]
Configuration for tab alignment was added in commit 1b6249baa5c866d16f6e8f5782c102473933dd48 and included in release [Tab Extension 1.2.0](https://github.com/DragonPlayerX/TabExtension/releases/tag/1.2.0).
